# -*- coding: utf-8 -*-
"""IOTfileAnalysisSparkSQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XL-jeWAdq5G8X7hoxZb5i2CG1mTYAnz2
"""

pip install pyspark

import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd
import pyspark
from pyspark.sql import DataFrame, SparkSession
from typing import List
import pyspark.sql.types as T
import pyspark.sql.functions as F
from pyspark import SparkFiles

spark = SparkSession \
       .builder \
       .appName("Week8_Assignment") \
       .getOrCreate()

spark

spark=SparkSession.builder.getOrCreate()

rawDF = spark.read.json("/content/iot_devices.json")
rawDF.show()

print("Number of Rows: ", rawDF.count())
print("Number of Columns", len(rawDF.columns))

type(rawDF)

rawDF.createOrReplaceTempView("IOT")
rawDF.show()

rawDF2 = spark.sql("SELECT cn, COUNT (device_id) AS Number FROM IOT GROUP BY Cn ORDER BY Cn")
rawDF2.show()

rawDF2 = spark.sql("SELECT cn, c02_level FROM IOT WHERE c02_level > 1400 ORDER BY c02_level DESC")
rawDF2.show()

rawDF3 = spark.sql("select cca3, count(distinct device_id) as device_id from IOT where lcd == 'red' group by cca3 order by device_id desc limit 100")
rawDF3.show()

rawDF3 = spark.sql("select cca3, count(distinct device_id) as device_id from IOT where battery_level == 0 group by cca3 order by device_id desc limit 100")
rawDF3.show()